name: zeus_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  http: ^1.1.0
  mobx: ^2.2.0
  provider: ^6.0.5
  validatorless: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
